function_name: mcp-yart-cfunc
service_account_id: ...
runtime: python312
entrypoint: index.handler
memory: 512m
timeout: 120s
source_dir: func
include_files:
  - index.py
  - requirements.txt
environment:
  mode: "inline"
  YART_FOLDER_ID: ...
  YART_API_KEY: ...
  static_key_id: ...
  static_key_secret: ...
  bucket: ...
  DOWNSIZE_FACTOR: "2"
